openapi: 3.0.1
info:
  contact:
    email: developer-access@brex.com
    name: Admin
    url: https://brex.com
  description: |2

    The transactions API lets you view your transactions, accounts, and statements.
  title: Transactions API
  version: "1.0"
  x-konfig-has-globally-required-security: true
servers:
- description: Production
  url: https://platform.brexapis.com
- description: "Staging (Note: This is not a sandbox. It will not work with customer\
    \ tokens.)"
  url: https://platform.staging.brexapps.com
security:
- OAuth2: []
tags:
- description: Endpoints for account data.
  name: Accounts
- description: Endpoints for transaction data.
  name: Transactions
paths:
  /v2/accounts/card:
    get:
      description: |2

        This endpoint lists all accounts of card type.
      operationId: Accounts_listCardAccounts
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsListCardAccountsResponse'
          description: listCardAccounts 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - accounts.card.readonly
      summary: |2

        List card accounts
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-card
      x-accepts: application/json
  /v2/accounts/card/primary/statements:
    get:
      description: |2

        This endpoint lists all finalized statements for the primary card account.
      operationId: Accounts_listPrimaryCardStatements
      parameters:
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Statement_'
          description: listPrimaryCardStatements 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - statements.card.readonly
      summary: "\nList primary card account statements. \n"
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-card-primary-statements
      x-accepts: application/json
  /v2/accounts/cash:
    get:
      description: |2

        This endpoint lists all the existing cash accounts with their status.
      operationId: Accounts_listCashAccounts
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_CashAccount_'
          description: listAccounts 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - accounts.cash.readonly
      summary: |2

        List cash accounts
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash
      x-accepts: application/json
  /v2/accounts/cash/primary:
    get:
      description: |2

        This endpoint returns the primary cash account with its status. There will always be only one primary account.
      operationId: Accounts_status
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CashAccount'
          description: getPrimaryAccount 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - accounts.cash.readonly
      summary: |2

        Get primary cash account
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-primary
      x-accepts: application/json
  /v2/accounts/cash/{id}:
    get:
      description: |2

        This endpoint returns the cash account associated with the provided ID with its status.
      operationId: Accounts_getCashAccount
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CashAccount'
          description: getAccount 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - accounts.cash.readonly
      summary: |2

        Get cash account by ID
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-id
      x-accepts: application/json
  /v2/accounts/cash/{id}/statements:
    get:
      description: |2

        This endpoint lists all finalized statements for the cash account by ID.
      operationId: Accounts_listCashStatements
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Statement_'
          description: listCashStatements 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - statements.cash.readonly
      summary: "\nList cash account statements.    \n"
      tags:
      - Accounts
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-id-statements
      x-accepts: application/json
  /v2/transactions/card/primary:
    get:
      description: |2

        This endpoint lists all settled transactions for all card accounts.
        Regular users may only fetch their own "PURCHASE","REFUND" and "CHARGEBACK" settled transactions.
      operationId: Transactions_listAllCardTransactions
      parameters:
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: user_ids
        required: false
        schema:
          items:
            type: string
          nullable: true
          type: array
        style: form
      - description: |2

          Shows only transactions with a `posted_at_date` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
        example: |2

          2022-12-12T23:59:59.999
        explode: true
        in: query
        name: posted_at_start
        required: false
        schema:
          format: date-time
          nullable: true
          type: string
        style: form
        x-konfig-original-example: |2

          2022-12-12T23:59:59.999
      - explode: true
        in: query
        name: "expand[]"
        required: false
        schema:
          description: "`expense_id` can be passed to `expand[]` query parameter to\
            \ get expanded, e.g., `?expand[]=expense_id`."
          items:
            type: string
          nullable: true
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_CardTransaction_'
          description: listPrimaryCardTransactions 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - transactions.card.readonly
      summary: |2

        List transactions for all card accounts.
      tags:
      - Transactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-transactions-card-primary
      x-accepts: application/json
  /v2/transactions/cash/{id}:
    get:
      description: |2

        This endpoint lists all transactions for the cash account with the selected ID.
      operationId: Transactions_listById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      - description: |2

          Shows only transactions with a `posted_at_date` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
        example: |2

          2022-12-12T23:59:59.999
        explode: true
        in: query
        name: posted_at_start
        required: false
        schema:
          format: date-time
          nullable: true
          type: string
        style: form
        x-konfig-original-example: |2

          2022-12-12T23:59:59.999
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_CashTransaction_'
          description: listCashTransactions 200 response
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - OAuth2:
        - transactions.cash.readonly
      summary: |2

        List transactions for the selected cash account.
      tags:
      - Transactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-transactions-cash-id
      x-accepts: application/json
components:
  schemas:
    CardAccount:
      example:
        account_limit: null
        current_statement_period:
          end_date: 2000-01-23
          start_date: 2000-01-23
        current_balance: null
        id: id
        available_balance: null
        status: ""
      properties:
        id:
          description: ID of the card account
          required:
          - "true"
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/Status'
          - nullable: true
        current_balance:
          $ref: '#/components/schemas/CardAccount_current_balance'
        available_balance:
          $ref: '#/components/schemas/CardAccount_current_balance'
        account_limit:
          $ref: '#/components/schemas/CardAccount_current_balance'
        current_statement_period:
          $ref: '#/components/schemas/StatementPeriod'
      required:
      - current_statement_period
      - id
      type: object
    CardTransaction:
      example:
        amount:
          amount: 0
          currency: currency
        initiated_at_date: 2000-01-23
        description: description
        posted_at_date: 2000-01-23
        merchant: null
        id: id
        card_metadata:
          key: card_metadata
        type: ""
        expense_id: expense_id
        card_id: card_id
      properties:
        description:
          description: Description of the transaction
          required:
          - "true"
          type: string
        id:
          type: string
        card_id:
          description: ID of the card used for the transaction. Null when type is
            REWARDS_CREDIT or COLLECTION.
          nullable: true
          type: string
        amount:
          $ref: '#/components/schemas/Money'
        initiated_at_date:
          description: ISO 8601 date string
          format: date
          required:
          - "true"
          type: string
        posted_at_date:
          description: ISO 8601 date string
          format: date
          required:
          - "true"
          type: string
        type:
          allOf:
          - $ref: '#/components/schemas/CardTransactionType'
          - nullable: true
        merchant:
          $ref: '#/components/schemas/CardTransaction_merchant'
        card_metadata:
          additionalProperties:
            type: string
          description: "\nSet of key value pairs associated with this object. Please\
            \ do not store any personally identifiable or sensitive information here.\n\
            Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values\
            \ cannot exceed 500 characters. \n"
          nullable: true
          type: object
        expense_id:
          description: The expense ID related to the card transaction.
          nullable: true
          type: string
      required:
      - amount
      - description
      - id
      - initiated_at_date
      - posted_at_date
      type: object
    CardTransactionType:
      enum:
      - PURCHASE
      - REFUND
      - CHARGEBACK
      - REWARDS_CREDIT
      - COLLECTION
      - BNPL_FEE
      type: string
    CashAccount:
      example:
        account_number: account_number
        name: name
        current_balance:
          amount: 0
          currency: currency
        id: id
        available_balance:
          amount: 0
          currency: currency
        routing_number: routing_number
        status: ""
        primary: true
      properties:
        id:
          description: ID of the cash account
          required:
          - "true"
          type: string
        name:
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/Status'
          - nullable: true
        current_balance:
          $ref: '#/components/schemas/Money'
        available_balance:
          $ref: '#/components/schemas/Money'
        account_number:
          type: string
        routing_number:
          type: string
        primary:
          description: Whether or not this account is the primary account. There will
            always be only one primary account.
          required:
          - "true"
          type: boolean
      required:
      - account_number
      - available_balance
      - current_balance
      - id
      - name
      - primary
      - routing_number
      type: object
      x-konfig-is-used-in-successful-response: true
    CashTransaction:
      example:
        amount: null
        initiated_at_date: 2000-01-23
        description: description
        posted_at_date: 2000-01-23
        id: id
        transfer_id: transfer_id
        type: ""
      properties:
        description:
          description: Description of the transaction
          required:
          - "true"
          type: string
        id:
          type: string
        amount:
          $ref: '#/components/schemas/CardAccount_current_balance'
        initiated_at_date:
          description: ISO 8601 date of when the payment is initiated
          format: date
          required:
          - "true"
          type: string
        posted_at_date:
          description: ISO 8601 date of when the payment is posted
          format: date
          required:
          - "true"
          type: string
        type:
          allOf:
          - $ref: '#/components/schemas/CashTransactionType'
          - nullable: true
        transfer_id:
          description: Transfer ID to fetch additional metadata about the transaction
            using `https://developer.brex.com/openapi/payments_api/#operation/getTransfersById`
          nullable: true
          type: string
      required:
      - description
      - id
      - initiated_at_date
      - posted_at_date
      type: object
    CashTransactionType:
      enum:
      - PAYMENT
      - DIVIDEND
      - FEE
      - ADJUSTMENT
      - INTEREST
      - CARD_COLLECTION
      - REWARDS_REDEMPTION
      - RECEIVABLES_OFFERS_ADVANCE
      - FBO_TRANSFER
      - RECEIVABLES_OFFERS_REPAYMENT
      - RECEIVABLES_OFFERS_COLLECTION
      - BREX_OPERATIONAL_TRANSFER
      - INTRA_CUSTOMER_ACCOUNT_BOOK_TRANSFER
      - BOOK_TRANSFER
      - CRYPTO_BRIDGE
      type: string
    Merchant:
      properties:
        raw_descriptor:
          description: Merchant descriptor
          required:
          - "true"
          type: string
        mcc:
          description: https://en.wikipedia.org/wiki/Merchant_category_code
          required:
          - "true"
          type: string
      required:
      - mcc
      - raw_descriptor
      type: object
    Money:
      description: |2

        Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
        of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
      example:
        amount: 0
        currency: currency
      properties:
        amount:
          description: "The amount of money, in the smallest denomination of the currency\
            \ indicated by currency. For example, when currency is USD, amount is\
            \ in cents."
          format: int64
          type: integer
        currency:
          description: "The type of currency, in ISO 4217 format. Default to USD if\
            \ not specified"
          nullable: true
          type: string
      type: object
    Page_CardTransaction_:
      example:
        next_cursor: next_cursor
        items:
        - amount:
            amount: 0
            currency: currency
          initiated_at_date: 2000-01-23
          description: description
          posted_at_date: 2000-01-23
          merchant: null
          id: id
          card_metadata:
            key: card_metadata
          type: ""
          expense_id: expense_id
          card_id: card_id
        - amount:
            amount: 0
            currency: currency
          initiated_at_date: 2000-01-23
          description: description
          posted_at_date: 2000-01-23
          merchant: null
          id: id
          card_metadata:
            key: card_metadata
          type: ""
          expense_id: expense_id
          card_id: card_id
      properties:
        next_cursor:
          nullable: true
          type: string
        items:
          items:
            $ref: '#/components/schemas/CardTransaction'
          type: array
      required:
      - items
      type: object
      x-konfig-is-used-in-successful-response: true
    Page_CashAccount_:
      example:
        next_cursor: next_cursor
        items:
        - account_number: account_number
          name: name
          current_balance:
            amount: 0
            currency: currency
          id: id
          available_balance:
            amount: 0
            currency: currency
          routing_number: routing_number
          status: ""
          primary: true
        - account_number: account_number
          name: name
          current_balance:
            amount: 0
            currency: currency
          id: id
          available_balance:
            amount: 0
            currency: currency
          routing_number: routing_number
          status: ""
          primary: true
      properties:
        next_cursor:
          nullable: true
          type: string
        items:
          items:
            $ref: '#/components/schemas/CashAccount'
          type: array
      required:
      - items
      type: object
      x-konfig-is-used-in-successful-response: true
    Page_CashTransaction_:
      example:
        next_cursor: next_cursor
        items:
        - amount: null
          initiated_at_date: 2000-01-23
          description: description
          posted_at_date: 2000-01-23
          id: id
          transfer_id: transfer_id
          type: ""
        - amount: null
          initiated_at_date: 2000-01-23
          description: description
          posted_at_date: 2000-01-23
          id: id
          transfer_id: transfer_id
          type: ""
      properties:
        next_cursor:
          nullable: true
          type: string
        items:
          items:
            $ref: '#/components/schemas/CashTransaction'
          type: array
      required:
      - items
      type: object
      x-konfig-is-used-in-successful-response: true
    Page_Statement_:
      example:
        next_cursor: next_cursor
        items:
        - period:
            end_date: 2000-01-23
            start_date: 2000-01-23
          end_balance: null
          id: id
          start_balance: null
        - period:
            end_date: 2000-01-23
            start_date: 2000-01-23
          end_balance: null
          id: id
          start_balance: null
      properties:
        next_cursor:
          nullable: true
          type: string
        items:
          items:
            $ref: '#/components/schemas/Statement'
          type: array
      required:
      - items
      type: object
      x-konfig-is-used-in-successful-response: true
    Statement:
      example:
        period:
          end_date: 2000-01-23
          start_date: 2000-01-23
        end_balance: null
        id: id
        start_balance: null
      properties:
        id:
          type: string
        start_balance:
          $ref: '#/components/schemas/CardAccount_current_balance'
        end_balance:
          $ref: '#/components/schemas/CardAccount_current_balance'
        period:
          $ref: '#/components/schemas/StatementPeriod'
      required:
      - id
      - period
      type: object
    StatementPeriod:
      example:
        end_date: 2000-01-23
        start_date: 2000-01-23
      properties:
        start_date:
          description: Start date of the statement period
          format: date
          required:
          - "true"
          type: string
        end_date:
          description: End date of the statement period
          format: date
          required:
          - "true"
          type: string
      required:
      - end_date
      - start_date
      type: object
    Status:
      enum:
      - ACTIVE
      type: string
    AccountsListCardAccountsResponse:
      items:
        $ref: '#/components/schemas/CardAccount'
      type: array
      x-konfig-is-used-in-successful-response: true
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-card:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-card-primary-statements:
      properties:
        cursor:
          nullable: true
          type: string
        limit:
          format: int32
          nullable: true
          type: integer
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - cursor
      - limit
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-primary:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-id:
      properties:
        id:
          type: string
      required:
      - id
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - id
    konfig-generated-schema-single-parameter-schema-get--v2-accounts-cash-id-statements:
      properties:
        id:
          type: string
        cursor:
          nullable: true
          type: string
        limit:
          format: int32
          nullable: true
          type: integer
      required:
      - id
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - id
      - cursor
      - limit
    konfig-generated-schema-single-parameter-schema-get--v2-transactions-card-primary:
      properties:
        cursor:
          nullable: true
          type: string
        limit:
          format: int32
          nullable: true
          type: integer
        user_ids:
          items:
            type: string
          nullable: true
          type: array
        posted_at_start:
          format: date-time
          nullable: true
          type: string
        expand[]:
          description: "`expense_id` can be passed to `expand[]` query parameter to\
            \ get expanded, e.g., `?expand[]=expense_id`."
          items:
            type: string
          nullable: true
          type: array
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - cursor
      - limit
      - user_ids
      - posted_at_start
      - "expand[]"
    konfig-generated-schema-single-parameter-schema-get--v2-transactions-cash-id:
      properties:
        id:
          type: string
        cursor:
          nullable: true
          type: string
        limit:
          format: int32
          nullable: true
          type: integer
        posted_at_start:
          format: date-time
          nullable: true
          type: string
      required:
      - id
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - id
      - cursor
      - limit
      - posted_at_start
    CardAccount_current_balance:
      allOf:
      - $ref: '#/components/schemas/Money'
      - nullable: true
    CardTransaction_merchant:
      allOf:
      - $ref: '#/components/schemas/Merchant'
      - nullable: true
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          scopes:
            openid: openid
            offline_access: offline access
            transactions.card.readonly: View card transaction data
            statements.card.readonly: View card statement data
            accounts.card.readonly: View card account data
            accounts.cash.readonly: View cash account data
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
      type: oauth2
      x-konfig-globally-required-security: true
x-explorer-enabled: false

